export const questions = [
  {
    id: 'age',
    text: 'Sa vjeç jeni?',
    type: 'radio',
    required: true,
    options: [
      { value: 'under18', label: 'Nën 18' },
      { value: '18-24', label: '18–24' },
      { value: '25-34', label: '25–34' },
      { value: '35-44', label: '35–44' },
      { value: '45-54', label: '45–54' },
      { value: '55plus', label: '55+' },
    ],
  },
  {
    id: 'gender',
    text: 'Gjinia juaj:',
    type: 'radio',
    required: true,
    options: [
      { value: 'male', label: 'Mashkull' },
      { value: 'female', label: 'Femër' },
      { value: 'other', label: 'Tjetër / Preferoj të mos përgjigjem' },
    ],
  },
  {
    id: 'visitFrequency',
    text: 'Sa shpesh vizitoni dentistin?',
    type: 'radio',
    required: true,
    options: [
      { value: 'every6months', label: 'Çdo 6 muaj' },
      { value: 'onceAYear', label: 'Një herë në vit' },
      { value: 'whenInPain', label: 'Vetëm kur kam dhimbje' },
      { value: 'never', label: 'Nuk kam vizituar ndonjëherë dentistin' },
    ],
  },
  {
    id: 'servicesInterest',
    text: 'Çfarë lloj shërbimesh dentare ju interesojnë më shumë? (Zgjidhni më shumë se një nëse dëshironi)',
    type: 'checkbox',
    required: true,
    options: [
      { value: 'routineCheckup', label: 'Kontroll rutinë dhe pastrim' },
      { value: 'fillings', label: 'Mbushje dhe trajtime kundër kaviteteve' },
      { value: 'orthodontics', label: 'Ortodonci (rregullim i dhëmbëve, aparate)' },
      { value: 'cosmetic', label: 'Estetikë dentare (zbardhje, faseta, etj.)' },
      { value: 'implants', label: 'Implantologji' },
      { value: 'other', label: 'Të tjera (Ju lutemi specifikoni)' },
    ],
  },
  {
    id: 'badExperience',
    text: 'A keni pasur ndonjëherë ndonjë përvojë të pakëndshme me një dentist?',
    type: 'radio',
    required: true,
    options: [
      { value: 'yes', label: 'Po' },
      { value: 'no', label: 'Jo' },
      { value: 'dontRemember', label: 'Nuk më kujtohet' },
    ],
  },
  {
    id: 'serviceImportance',
    text: 'Sa e rëndësishme është për ju cilësia e shërbimit krahasuar me çmimin?',
    type: 'radio',
    required: true,
    options: [
      { value: 'veryImportant', label: 'Shumë e rëndësishme' },
      { value: 'qualityMoreImportant', label: 'Më e rëndësishme cilësia' },
      { value: 'priceMoreImportant', label: 'Më i rëndësishëm çmimi' },
      { value: 'bothEquallyImportant', label: 'Të dy janë po aq të rëndësishëm' },
    ],
  },
  {
    id: 'clinicSelection',
    text: 'Si e zgjidhni zakonisht një klinikë dentare?',
    type: 'radio',
    required: true,
    options: [
      { value: 'recommendations', label: 'Rekomandime nga miqtë/familja' },
      { value: 'socialMedia', label: 'Rrjetet sociale' },
      { value: 'googleSearch', label: 'Kërkim në Google / internet' },
      { value: 'convenientLocation', label: 'Lokacioni i përshtatshëm' },
      { value: 'previousExperiences', label: 'Përvojat e mëparshme' },
    ],
  },
  {
    id: 'financialInterest',
    text: 'A do të ishit të interesuar për oferta apo plane financiare për shërbime dentare?',
    type: 'radio',
    required: true,
    options: [
      { value: 'yes', label: 'Po' },
      { value: 'no', label: 'Jo' },
      { value: 'maybe', label: 'Ndoshta, në varësi të ofertës' },
    ],
  },
];